name: Deploy to AWS Lightsail

# Event triggered whenever a new release is published in GitHub
on:
#  push:
#    branches:
#      - main
  release:
    types: [published]

jobs:
  Call-Linting:
    uses: ./.github/workflows/reuse_linting.yml
  Call-Testing:
    uses: ./.github/workflows/reuse_testing.yml
    secrets: inherit
  Deploy_AWS_Lightsail:
    needs: [Call-Linting, Call-Testing]
    uses: ./.github/workflows/reuse_push_aws_ecr.yml
    secrets: inherit