name: Build/push to AWS ECR and deploy to AWS Lightsail

# Event triggered whenever a new release is published in GitHub
on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  Linting:
    uses: ./.github/workflows/reuse_linting.yml
  Testing:
    uses: ./.github/workflows/reuse_testing.yml
    secrets: inherit
  Deploy_AWS_Lightsail:
    needs: [Call-linting-workflow, Call-testing-workflow]
    uses: ./.github/workflows/reuse_push_aws_ecr.yml
    secrets: inherit