name: Deploy to AWS Lambda

# Event triggered whenever a change on the branch prod_lambda happens
on:
  push:
    branches:
      - prod_lambda

jobs:
  Call-Linting:
    uses: ./.github/workflows/reuse_linting.yml
  Call-Testing:
    uses: ./.github/workflows/reuse_testing.yml
    secrets: inherit
  Deploy_AWS_Lambda:
    needs: [Call-Linting, Call-Testing]
    uses: ./.github/workflows/reuse_deploy_aws_lambda.yml
    secrets: inherit