name: Linting and Testing

# Event triggered whenever push is preformed including all branches except main branch
on:
  push:
    branches-ignore:
      - main
      - prod_lambda

jobs:
  Call-Linting:
    uses: ./.github/workflows/reuse_linting.yml
  Call-Testing:
    needs: Call-Linting
    uses: ./.github/workflows/reuse_testing.yml
    secrets: inherit
