name: Linting and Testing

# Event triggered whenever push is preformed including all branches except main branch
on:
  push:
    branches-ignore:
      - main

jobs:
  Call-Linting:
    uses: ./.github/workflows/reuse_linting.yml
  Call-Testing:
    uses: ./.github/workflows/reuse_testing.yml
    secrets: inherit
  Call-testing-workflow-again:
    needs: [Call-Linting, Call-Testing]
    uses: ./.github/workflows/reuse_testing.yml
    secrets: inherit
